const Slot = require('../models/Slot');
const User = require('../models/User');

const TOTAL_DAYS = 20;

const generateTimeSlots = (
  startTime,
  endTime,
  slotDuration,
  breakStart,
  breakEnd,
  date,
  shift
) => {
  const slots = [];

  const start = new Date(`${date}T${startTime}:00`);
  const end = new Date(`${date}T${endTime}:00`);

  const breakStartTime = breakStart
    ? new Date(`${date}T${breakStart}:00`)
    : null;

  const breakEndTime = breakEnd
    ? new Date(`${date}T${breakEnd}:00`)
    : null;

  const duration = slotDuration || 15;

  let current = new Date(start);

  while (current < end) {
    if (
      breakStartTime &&
      breakEndTime &&
      current >= breakStartTime &&
      current < breakEndTime
    ) {
      current = new Date(breakEndTime);
      continue;
    }

    slots.push({
      slotTime: current.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: true,
      }),
      shift,
    });

    current = new Date(current.getTime() + duration * 60000);
  }

  return slots;
};

const generateSlotsForDoctor = async (doctorId, startDate) => {
  const doctor = await User.findById(doctorId);

  if (!doctor) {
    throw new Error('Doctor not found');
  }

  if (!doctor.isActive) {
    return {
      created: 0,
      skipped: true,
    };
  }

  const timing = doctor.timing || {
    morning: {
      start: '09:00',
      end: '12:00',
      enabled: true,
    },
    evening: {
      start: '16:00',
      end: '20:00',
      enabled: true,
    },
    slotDuration: 15,
    break: {
      start: '13:00',
      end: '14:00',
      enabled: true,
    },
  };

  let totalCreated = 0;

  for (let day = 0; day < TOTAL_DAYS; day++) {

    const dateObj = new Date(startDate);
    dateObj.setDate(dateObj.getDate() + day);

    const slotDate = dateObj.toISOString().split('T')[0];

    const exists = await Slot.exists({
      doctor: doctorId,
      slotDate,
    });

    if (exists) {
      continue;
    }

    let allSlots = [];

    if (timing.morning.enabled) {
      allSlots.push(
        ...generateTimeSlots(
          timing.morning.start,
          timing.morning.end,
          timing.slotDuration,
          timing.break.enabled ? timing.break.start : null,
          timing.break.enabled ? timing.break.end : null,
          slotDate,
          'morning'
        )
      );
    }

    if (timing.evening.enabled) {
      allSlots.push(
        ...generateTimeSlots(
          timing.evening.start,
          timing.evening.end,
          timing.slotDuration,
          timing.break.enabled ? timing.break.start : null,
          timing.break.enabled ? timing.break.end : null,
          slotDate,
          'evening'
        )
      );
    }

    // Skip past time slots for today only
    const now = new Date();

    let slotsToCreate = allSlots.filter(slot => {

      if (slotDate !== now.toISOString().split('T')[0]) {
        return true;
      }

      const match = slot.slotTime.match(/(\d+):(\d+)\s*([AP]M)/i);

      if (!match) return true;

      let hour = parseInt(match[1]);

      const minute = parseInt(match[2]);

      const ampm = match[3].toUpperCase();

      if (ampm === 'PM' && hour !== 12) hour += 12;

      if (ampm === 'AM' && hour === 12) hour = 0;

      const slotMinutes = hour * 60 + minute;

      const currentMinutes =
        now.getHours() * 60 + now.getMinutes();

      return slotMinutes > currentMinutes;

    });

    if (
      doctor.maxAppointmentsPerDay &&
      slotsToCreate.length > doctor.maxAppointmentsPerDay
    ) {
      slotsToCreate = slotsToCreate.slice(
        0,
        doctor.maxAppointmentsPerDay
      );
    }

    if (slotsToCreate.length) {

      await Slot.insertMany(
        slotsToCreate.map(slot => ({
          doctor: doctorId,
          slotDate,
          slotTime: slot.slotTime,
          shift: slot.shift,
          status: 'available',
          isAutoGenerated: true,
        }))
      );

      totalCreated += slotsToCreate.length;
    }
  }

  return {
    created: totalCreated,
    skipped: false,
  };
};

module.exports = generateSlotsForDoctor;