// utils/generateSlotsForDoctor.js
const Slot = require('../models/Slot');
const User = require('../models/User');

const generateTimeSlots = (startTime, endTime, slotDuration, breakStart, breakEnd, date, shift) => {
  const slots = [];
  const start = new Date(`${date}T${startTime}:00`);
  const end = new Date(`${date}T${endTime}:00`);
  const breakStartTime = breakStart ? new Date(`${date}T${breakStart}:00`) : null;
  const breakEndTime = breakEnd ? new Date(`${date}T${breakEnd}:00`) : null;
  const duration = slotDuration || 15;

  let current = new Date(start);

  while (current < end) {
    // Check break time
    if (breakStartTime && breakEndTime) {
      if (current >= breakStartTime && current < breakEndTime) {
        current = new Date(breakEndTime);
        continue;
      }
    }

    const slotTime = current.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
    });

    slots.push({
      slotTime,
      shift,
    });

    current = new Date(current.getTime() + duration * 60000);
  }

  return slots;
};

const generateSlotsForDoctor = async (doctorId, slotDate) => {
  try {
    // Get doctor with timing info
    const doctor = await User.findById(doctorId);
    if (!doctor) {
      throw new Error('Doctor not found');
    }

    // Check if doctor is active
    if (!doctor.isActive) {
      return { created: 0, message: 'Doctor is inactive' };
    }

    // Check if slots already exist for this date
    const existingSlots = await Slot.find({
      doctor: doctorId,
      slotDate: slotDate,
    });

    if (existingSlots.length > 0) {
      return {
        created: 0,
        skipped: true,
        message: `Slots already exist for ${slotDate}`,
      };
    }

    const timing = doctor.timing || {
      morning: { start: '09:00', end: '12:00', enabled: true },
      evening: { start: '16:00', end: '20:00', enabled: true },
      slotDuration: 15,
      break: { start: '13:00', end: '14:00', enabled: true },
    };

    const allSlots = [];
    const today = new Date().toISOString().split('T')[0];
    const isToday = slotDate === today;
    const currentTime = new Date();

    // Generate morning slots
    if (timing.morning.enabled) {
      const morningSlots = generateTimeSlots(
        timing.morning.start,
        timing.morning.end,
        timing.slotDuration,
        timing.break.enabled ? timing.break.start : null,
        timing.break.enabled ? timing.break.end : null,
        slotDate,
        'morning'
      );
      allSlots.push(...morningSlots);
    }

    // Generate evening slots
    if (timing.evening.enabled) {
      const eveningSlots = generateTimeSlots(
        timing.evening.start,
        timing.evening.end,
        timing.slotDuration,
        timing.break.enabled ? timing.break.start : null,
        timing.break.enabled ? timing.break.end : null,
        slotDate,
        'evening'
      );
      allSlots.push(...eveningSlots);
    }

    // Filter slots for today (only future slots)
    const slotsToCreate = [];
    for (const slot of allSlots) {
      if (isToday) {
        const slotTime = new Date(`${slotDate}T${slot.slotTime}`);
        // Convert to 24-hour for comparison
        const slotHour = parseInt(slot.slotTime.split(':')[0]);
        const slotMinute = parseInt(slot.slotTime.split(':')[1].split(' ')[0]);
        const isPM = slot.slotTime.includes('PM');
        const slotDateObj = new Date();
        slotDateObj.setHours(isPM ? slotHour + 12 : slotHour, slotMinute, 0);

        // Skip past slots
        if (slotDateObj <= currentTime) {
          continue;
        }
      }

      slotsToCreate.push({
        doctor: doctorId,
        slotDate: slotDate,
        slotTime: slot.slotTime,
        status: 'available',
        shift: slot.shift,
        isAutoGenerated: true,
      });
    }

    // Check max appointments per day limit
    if (slotsToCreate.length > doctor.maxAppointmentsPerDay) {
      // Only take first N slots
      slotsToCreate.length = doctor.maxAppointmentsPerDay;
    }

    if (slotsToCreate.length > 0) {
      await Slot.insertMany(slotsToCreate);
    }

    return {
      created: slotsToCreate.length,
      skipped: false,
      message: `${slotsToCreate.length} slots created for ${slotDate}`,
    };
  } catch (error) {
    console.error('Error generating slots:', error);
    throw error;
  }
};

module.exports = generateSlotsForDoctor;