const mongoose = require('mongoose');

const slotSchema = new mongoose.Schema(
  {
    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    slotDate: {
      type: String, // YYYY-MM-DD format
      required: true,
    },

    slotTime: {
      type: String, // '09:00 AM' format
      required: true,
    },

    status: {
      type: String,
      enum: ['available', 'unavailable', 'booked', 'completed'],
      default: 'available',
    },

    // Which shift this slot belongs to
    shift: {
      type: String,
      enum: ['morning', 'evening'],
      required: true,
    },

    // Appointment reference if booked
    appointmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Appointment',
      default: null,
    },

    // Is this slot generated automatically
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for better performance
slotSchema.index({ doctor: 1, slotDate: 1, slotTime: 1 });
slotSchema.index({ slotDate: 1, status: 1 });
slotSchema.index({ doctor: 1, status: 1 });

module.exports = mongoose.model('Slot', slotSchema);